import Foundation

extension L10n {
    // MARK: - Screenshot

    static var cmdScreenshotRegionTitle: String { loc("cmd.screenshot.region.title") }
    static var cmdScreenshotRegionSubtitle: String { loc("cmd.screenshot.region.subtitle") }
    static var cmdScreenshotScrollingTitle: String { loc("cmd.screenshot.scrolling.title") }
    static var cmdScreenshotScrollingSubtitle: String { loc("cmd.screenshot.scrolling.subtitle") }
    static var cmdScreenshotWindowTitle: String { loc("cmd.screenshot.window.title") }
    static var cmdScreenshotWindowSubtitle: String { loc("cmd.screenshot.window.subtitle") }
    static var cmdScreenshotDisplayTitle: String { loc("cmd.screenshot.display.title") }
    static var cmdScreenshotDisplaySubtitle: String { loc("cmd.screenshot.display.subtitle") }
    static var cmdScreenshotHistoryTitle: String { loc("cmd.screenshot.history.title") }
    static var cmdScreenshotHistorySubtitle: String { loc("cmd.screenshot.history.subtitle") }
    static var cmdScreenshotEditTitle: String { loc("cmd.screenshot.edit.title") }
    static var cmdScreenshotEditSubtitle: String { loc("cmd.screenshot.edit.subtitle") }
    static var cmdScreenshotOCRTitle: String { loc("cmd.screenshot.ocr.title") }
    static var cmdScreenshotOCRSubtitle: String { loc("cmd.screenshot.ocr.subtitle") }
    static var cmdScreenshotTranslateTitle: String { loc("cmd.screenshot.translate.title") }
    static var cmdScreenshotTranslateSubtitle: String { loc("cmd.screenshot.translate.subtitle") }
    static var cmdScreenshotPinTitle: String { loc("cmd.screenshot.pin.title") }
    static var cmdScreenshotPinSubtitle: String { loc("cmd.screenshot.pin.subtitle") }
    static var screenshotOutputCopy: String { loc("screenshot.output.copy") }
    static var screenshotOutputSave: String { loc("screenshot.output.save") }
    static var screenshotOutputCopyAndSave: String { loc("screenshot.output.copy.and.save") }
    static var screenshotOverlayRegionHint: String { loc("screenshot.overlay.region.hint") }
    static var screenshotOverlayWindowHint: String { loc("screenshot.overlay.window.hint") }
    static var screenshotOverlayDisplayHint: String { loc("screenshot.overlay.display.hint") }
    static var screenshotClipboardName: String { loc("screenshot.clipboard.name") }
    static var screenshotErrorTitle: String { loc("screenshot.error.title") }
    static var screenshotErrorPermissionDenied: String { loc("screenshot.error.permission.denied") }
    static var screenshotOpenSettings: String { loc("screenshot.open.settings") }
    static var screenshotErrorNoDisplays: String { loc("screenshot.error.no.displays") }
    static var screenshotErrorDisplayUnavailable: String { loc("screenshot.error.display.unavailable") }
    static var screenshotErrorCaptureFailed: String { loc("screenshot.error.capture.failed") }
    static var screenshotErrorInvalidSelection: String { loc("screenshot.error.invalid.selection") }
    static var screenshotErrorEncoding: String { loc("screenshot.error.encoding") }
    static var screenshotOCRImageUnavailable: String { loc("screenshot.ocr.image.unavailable") }
    static var screenshotOCRNoText: String { loc("screenshot.ocr.no.text") }
    static var screenshotOCRCopiedTitle: String { loc("screenshot.ocr.copied.title") }
    static var screenshotOCRCopiedMessage: String { loc("screenshot.ocr.copied.message") }
    static var screenshotOCRErrorTitle: String { loc("screenshot.ocr.error.title") }
    static var screenshotQRNotFound: String { loc("screenshot.qr.not.found") }
    static var screenshotQRErrorTitle: String { loc("screenshot.qr.error.title") }
    static var screenshotQRResultTitle: String { loc("screenshot.qr.result.title") }
    static var screenshotQROpen: String { loc("screenshot.qr.open") }
    static var screenshotQRImportOTPTitle: String { loc("screenshot.qr.import.otp.title") }
    static var screenshotQRImportOTPMessage: String { loc("screenshot.qr.import.otp.message") }
    static var screenshotQRImportOTPConfirm: String { loc("screenshot.qr.import.otp.confirm") }
    static var screenshotQRImportOTPFailed: String { loc("screenshot.qr.import.otp.failed") }
    static var prefsScreenshotPageCapture: String { loc("prefs.screenshot.page.capture") }
    static var prefsScreenshotPageScrolling: String { loc("prefs.screenshot.page.scrolling") }
    static var prefsScreenshotPageOutput: String { loc("prefs.screenshot.page.output") }
    static var prefsScreenshotPageShortcuts: String { loc("prefs.screenshot.page.shortcuts") }
    static var prefsScreenshotPageOCR: String { loc("prefs.screenshot.page.ocr") }
    static var prefsScreenshotPageHistory: String { loc("prefs.screenshot.page.history") }
    static var prefsScreenshotEnabledTitle: String { loc("prefs.screenshot.enabled.title") }
    static var prefsScreenshotEnabledSubtitle: String { loc("prefs.screenshot.enabled.subtitle") }
    static var prefsScreenshotDefaultModeTitle: String { loc("prefs.screenshot.default.mode.title") }
    static var prefsScreenshotDefaultModeSubtitle: String { loc("prefs.screenshot.default.mode.subtitle") }
    static var prefsScreenshotRegionHotkeyTitle: String { loc("prefs.screenshot.region.hotkey.title") }
    static var prefsScreenshotRegionHotkeySubtitle: String { loc("prefs.screenshot.region.hotkey.subtitle") }
    static var prefsScreenshotScrollingHotkeyTitle: String { loc("prefs.screenshot.scrolling.hotkey.title") }
    static var prefsScreenshotScrollingHotkeySubtitle: String { loc("prefs.screenshot.scrolling.hotkey.subtitle") }
    static var prefsScreenshotEditHotkeyTitle: String { loc("prefs.screenshot.edit.hotkey.title") }
    static var prefsScreenshotEditHotkeySubtitle: String { loc("prefs.screenshot.edit.hotkey.subtitle") }
    static var prefsScreenshotWindowHotkeyTitle: String { loc("prefs.screenshot.window.hotkey.title") }
    static var prefsScreenshotWindowHotkeySubtitle: String { loc("prefs.screenshot.window.hotkey.subtitle") }
    static var prefsScreenshotDisplayHotkeyTitle: String { loc("prefs.screenshot.display.hotkey.title") }
    static var prefsScreenshotDisplayHotkeySubtitle: String { loc("prefs.screenshot.display.hotkey.subtitle") }
    static var prefsScreenshotOutputTitle: String { loc("prefs.screenshot.output.title") }
    static var prefsScreenshotOutputSubtitle: String { loc("prefs.screenshot.output.subtitle") }
    static var prefsScreenshotFormatTitle: String { loc("prefs.screenshot.format.title") }
    static var prefsScreenshotFormatSubtitle: String { loc("prefs.screenshot.format.subtitle") }
    static var prefsScreenshotQualityTitle: String { loc("prefs.screenshot.quality.title") }
    static var prefsScreenshotQualitySubtitle: String { loc("prefs.screenshot.quality.subtitle") }
    static var prefsScreenshotDirectoryTitle: String { loc("prefs.screenshot.directory.title") }
    static var prefsScreenshotDirectoryDefault: String { loc("prefs.screenshot.directory.default") }
    static var prefsScreenshotDirectoryChoose: String { loc("prefs.screenshot.directory.choose") }
    static var prefsScreenshotFileNameTitle: String { loc("prefs.screenshot.filename.title") }
    static var prefsScreenshotFileNameSubtitle: String { loc("prefs.screenshot.filename.subtitle") }
    static var prefsScreenshotSoundTitle: String { loc("prefs.screenshot.sound.title") }
    static var prefsScreenshotSoundSubtitle: String { loc("prefs.screenshot.sound.subtitle") }
    static var prefsScreenshotPostActionsTitle: String { loc("prefs.screenshot.post.actions.title") }
    static var prefsScreenshotPostActionsSubtitle: String { loc("prefs.screenshot.post.actions.subtitle") }
    static var prefsScreenshotPostActionsDurationTitle: String { loc("prefs.screenshot.post.actions.duration.title") }
    static var prefsScreenshotPostActionsDurationSubtitle: String { loc("prefs.screenshot.post.actions.duration.subtitle") }
    static var prefsScreenshotPostActionsNever: String { loc("prefs.screenshot.post.actions.never") }
    static var prefsScreenshotPostActionsSeconds: String { loc("prefs.screenshot.post.actions.seconds") }
    static var prefsScreenshotOCRIndexTitle: String { loc("prefs.screenshot.ocr.index.title") }
    static var prefsScreenshotOCRIndexSubtitle: String { loc("prefs.screenshot.ocr.index.subtitle") }
    static var postCaptureSave: String { loc("screenshot.post.capture.save") }
    static var prefsScreenshotWindowShadowTitle: String { loc("prefs.screenshot.window.shadow.title") }
    static var prefsScreenshotWindowShadowSubtitle: String { loc("prefs.screenshot.window.shadow.subtitle") }
    static var prefsScreenshotHistoryLimitTitle: String { loc("prefs.screenshot.history.limit.title") }
    static var prefsScreenshotHistoryLimitSubtitle: String { loc("prefs.screenshot.history.limit.subtitle") }
    static var prefsScreenshotHistoryLimitValue: String { loc("prefs.screenshot.history.limit.value") }
    static var prefsScreenshotRetentionDaysTitle: String { loc("prefs.screenshot.retention.days.title") }
    static var prefsScreenshotRetentionDaysSubtitle: String { loc("prefs.screenshot.retention.days.subtitle") }
    static var prefsScreenshotRetentionDaysValue: String { loc("prefs.screenshot.retention.days.value") }
    static var prefsScreenshotStorageLimitTitle: String { loc("prefs.screenshot.storage.limit.title") }
    static var prefsScreenshotStorageLimitSubtitle: String { loc("prefs.screenshot.storage.limit.subtitle") }
    static var prefsScreenshotStorageLimitValue: String { loc("prefs.screenshot.storage.limit.value") }
    static var prefsScreenshotRetentionUnlimited: String { loc("prefs.screenshot.retention.unlimited") }
    static var prefsScreenshotOCRLanguagesTitle: String { loc("prefs.screenshot.ocr.languages.title") }
    static var prefsScreenshotOCRLanguagesSubtitle: String { loc("prefs.screenshot.ocr.languages.subtitle") }
    static var prefsScreenshotOCRChinese: String { loc("prefs.screenshot.ocr.chinese") }
    static var prefsScreenshotOCREnglish: String { loc("prefs.screenshot.ocr.english") }
    static var screenshotHistoryTitle: String { loc("screenshot.history.title") }
    static var screenshotHistoryCount: String { loc("screenshot.history.count") }
    static var screenshotHistoryEmptyTitle: String { loc("screenshot.history.empty.title") }
    static var screenshotHistoryEmptySubtitle: String { loc("screenshot.history.empty.subtitle") }
    static var screenshotHistoryOpenFolder: String { loc("screenshot.history.open.folder") }
    static var screenshotHistoryClear: String { loc("screenshot.history.clear") }
    static var screenshotHistoryClearTitle: String { loc("screenshot.history.clear.title") }
    static var screenshotHistoryClearMessage: String { loc("screenshot.history.clear.message") }
    static var screenshotHistoryClearConfirm: String { loc("screenshot.history.clear.confirm") }
    static var screenshotHistorySearch: String { loc("screenshot.history.search") }
    static var historyLayoutGrid: String { loc("history.layout.grid") }
    static var historyLayoutList: String { loc("history.layout.list") }
    static var screenshotKindRegion: String { loc("screenshot.kind.region") }
    static var screenshotKindScrolling: String { loc("screenshot.kind.scrolling") }
    static var screenshotKindWindow: String { loc("screenshot.kind.window") }
    static var screenshotKindDisplay: String { loc("screenshot.kind.display") }
    static var screenshotKindEdited: String { loc("screenshot.kind.edited") }
    static var scrollingCaptureTitle: String { loc("scrolling.capture.title") }
    static var scrollingCapturePreparing: String { loc("scrolling.capture.preparing") }
    static var scrollingCapturePaused: String { loc("scrolling.capture.paused") }
    static var scrollingCaptureScrollHint: String { loc("scrolling.capture.scroll.hint") }
    static var scrollingCaptureProgress: String { loc("scrolling.capture.progress") }
    static var scrollingCapturePause: String { loc("scrolling.capture.pause") }
    static var scrollingCaptureResume: String { loc("scrolling.capture.resume") }
    static var scrollingCaptureAuto: String { loc("scrolling.capture.auto") }
    static var scrollingCaptureManual: String { loc("scrolling.capture.manual") }
    static var scrollingCaptureFinish: String { loc("scrolling.capture.finish") }
    static var scrollingCaptureErrorLiveFrame: String { loc("scrolling.capture.error.live.frame") }
    static var scrollingCaptureErrorNoOverlap: String { loc("scrolling.capture.error.no.overlap") }
    static var scrollingCaptureErrorFinalComposition: String { loc("scrolling.capture.error.final.composition") }
    static var scrollingCaptureReducedImageTitle: String { loc("scrolling.capture.reduced.image.title") }
    static var scrollingCaptureReducedImageMessage: String { loc("scrolling.capture.reduced.image.message") }
    static var scrollingCaptureReachedMaximumHeight: String { loc("scrolling.capture.maximum.height") }
    static var scrollingCaptureReachedMaximumPixels: String { loc("scrolling.capture.maximum.pixels") }
    static var scrollingCaptureAccessibilityTitle: String { loc("scrolling.capture.accessibility.title") }
    static var scrollingCaptureAccessibilityMessage: String { loc("scrolling.capture.accessibility.message") }
    static var scrollingCaptureEditLimitTitle: String { loc("scrolling.capture.edit.limit.title") }
    static var scrollingCaptureEditLimitMessage: String { loc("scrolling.capture.edit.limit.message") }
    static var scrollingCaptureSpeedSlow: String { loc("scrolling.capture.speed.slow") }
    static var scrollingCaptureSpeedMedium: String { loc("scrolling.capture.speed.medium") }
    static var scrollingCaptureSpeedFast: String { loc("scrolling.capture.speed.fast") }
    static var prefsScrollingCaptureMaximumHeightTitle: String { loc("prefs.scrolling.capture.maximum.height.title") }
    static var prefsScrollingCaptureMaximumHeightSubtitle: String { loc("prefs.scrolling.capture.maximum.height.subtitle") }
    static var prefsScrollingCaptureMaximumPixelsTitle: String { loc("prefs.scrolling.capture.maximum.pixels.title") }
    static var prefsScrollingCaptureMaximumPixelsSubtitle: String { loc("prefs.scrolling.capture.maximum.pixels.subtitle") }
    static var prefsScrollingCapturePixelsValue: String { loc("prefs.scrolling.capture.pixels.value") }
    static var prefsScrollingCaptureMegapixelsValue: String { loc("prefs.scrolling.capture.megapixels.value") }
    static var prefsScrollingCaptureFrozenHeaderTitle: String { loc("prefs.scrolling.capture.frozen.header.title") }
    static var prefsScrollingCaptureFrozenHeaderSubtitle: String { loc("prefs.scrolling.capture.frozen.header.subtitle") }
    static var prefsScrollingCaptureAutoTitle: String { loc("prefs.scrolling.capture.auto.title") }
    static var prefsScrollingCaptureAutoSubtitle: String { loc("prefs.scrolling.capture.auto.subtitle") }
    static var prefsScrollingCaptureSpeedTitle: String { loc("prefs.scrolling.capture.speed.title") }
    static var prefsScrollingCaptureSpeedSubtitle: String { loc("prefs.scrolling.capture.speed.subtitle") }

}
